---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  radon:
    enabled: true
  pep8:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
- tests/**/*
