language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
  - pip install coveralls
script:
  - cd tests
  - unzip ../search.zip -d .
  - coverage run --omit test.py test.py -v
after_success:
  - coveralls
notifications:
  email: false
